### ISSUE TITLE
Set Attribute to null instead of proxy object

### ISSUE THREAD

**Issue by bruenisholma** [lbovet/hybind#18]
Hybind creates proxy objects. Also when the server sent null values. The expected behaviour is that Hybind also sets the attribute to null when the server sent a null value.
This avoids Null-Check-Issues where a null value is expected but an empty proxy object is given which evaluates to true instead of false.

**Comment by lbovet** [comment]
Fixed. I will release npm+webjar tonight. Should be avail tomorrow.

**Comment by lbovet** [comment]
Now available on npm and webjars
