### ISSUE TITLE
Page object in Spring Data Rest

### ISSUE THREAD

**Issue by maksaimer** [lbovet/hybind#2]
Hi.

What about page field in json? How i can provide access to it?

For example, I have response from my Spring Data Rest server with page field:

`"page" : {
    "size" : 3,
    "totalElements" : 4,
    "totalPages" : 2,
    "number" : 0
  }`

**Comment by maksaimer** [comment]
May be add $page to array?

**Comment by lbovet** [comment]
PR about this: https://github.com/lbovet/hybind/pull/3
I commented this PR. Maybe better to have $metadata.page
or some better naming than $metadata? $obj, $resource ?

**Comment by maksaimer** [comment]
I think $metadata best way to do this

**Comment by lbovet** [comment]
Added as $resource property in collections ($metadata was too specific). Available in https://github.com/lbovet/hybind/releases/tag/v1.2.0
