### ISSUE TITLE
jQuery.Deferred exception: Cannot read property '_links' of undefined

### ISSUE THREAD

**Issue by jinyoung** [lbovet/hybind#20]
Hi, thank you for fantastic library!

When I try to use $create() function in loaded HAL object, there's an error occurs - 

```
            var backend = hybind("http://localhost:8080");
            var tickets = []; 
            backend.$bind("ticket", tickets);

            tickets.$load().then(function(){
                tickets[0].supports.$create(    // Error comes here
                    {content: "aaa"}
                );
            }
```

My entity classes are

```
public class Ticket{
    @Id
    @GeneratedValue
    Long id;
    Date issueDate;
    String type;
    String title;
    String content;
    String status;

    @OneToMany
    List<Support> supports;
}

public class Support {

    @Id
    @GeneratedValue
    Long id;
    Date supportDate;
    String content;
    String assignee;

    @ManyToOne
    Ticket ticket;
}
```
I found Spring Data Rest doesn't support this kind of POST action for generated URI by @OneToMany - http://localhost:8080/ticket/2/supports 

Can this be a reason for this error?

My full source code can be found here: https://github.com/TheOpenCloudEngine/mw4-example-crm

Is there any solution?

Thanks

**Comment by jinyoung** [comment]
Attached is hybind source that occurs the error:
```
defProp(obj, '$create', function(item, params, opts) {
          var d;
          d = deferred();
          req({
            method: 'POST',
            url: selfLink(obj),
            data: item || {}
          }, params, opts).then(function(data) {
            if (item) {
              extend(item, data);
            }
            if (item == null) {
              item = data;
            }
            enrich(item, data._links.self.href);     <------- here
            delete item._links;
            return d.resolve(item);
          }, d.reject);
          return promise(d);
        });
```

**Comment by lbovet** [comment]
That's right, POST is for creating entities, not associations. You need to create first the support entity with something like `var s = backend.$bind("supports").$create({content: "aaa"});`
then attach it to the ticket `tickets[0].$load().support.$set(s);`

**Comment by jinyoung** [comment]
I got it. Thank you.

**Comment by jinyoung** [comment]
Hi, Ibovet

I have another question about linking two entities

As you mentioned above:

```
var s = backend.$bind("supports").$create({content: "aaa"});     # in this line, foreign key contraint matters
tickets[0].$load().support.$set(s);
```

It looks reasonable, but in my case, the support cannot be created until it has no ticket information since the two entities are grouped by foreign-key constraint.

Is there any possible solution for linking two resource before it is POSTed? 

Thank you
