### ISSUE TITLE
linking two entities

### ISSUE THREAD

**Issue by jinyoung** [lbovet/hybind#22]
Hi, Ibovet

I have another question about linking two entities

As you mentioned:

```
var s = backend.$bind("supports").$create({content: "aaa"});     # in this line, foreign key contraint matters
tickets[0].$load().support.$set(s);
```

It looks reasonable, but in my case, the support cannot be created until it has no ticket information since the two entities are grouped by foreign-key constraint.

Is there any possible solution for linking two resource before it is POSTed? 

Thank you

**Comment by lbovet** [comment]
This would imply that the underlying implementation support this. AFAIK, there is no support in spring-data-rest (https://docs.spring.io/spring-data/rest/docs/3.0.2.RELEASE/reference/html/) to put and link an associated resource at once. Thus, hybind has no support for such a feature.
Your foreign key must be nullable so that `$create works`.

**Comment by jinyoung** [comment]
Thank you for your response.

My case is there's already existing referencing data and linking it's reference to sub data:

Look at this HTTPie command:
```
http localhost:8080/tickets title="a"   # returns _self link as 'http://localhost:8080/tickets/1'
http localhost:8080/supports ticket="http://localhost:8080/tickets/1" personInCharge="test@test.com"   # how to do this?
```
It works in Spring Data Rest without setting nullable for the foreignKey (ticket).
What I want to know is how to express the second line ajax call in Hybind.

Thanks

**Comment by jinyoung** [comment]
Or if you can provide the _links.self.href attribute for the mapped object, I can extend the hybind or manually implement it by:

```
backend.$bind("supports").$create({content: "aaa", ticket: ticket._links.self.href});
```

**Comment by lbovet** [comment]
If you already have the ticket and it is bound (you got it with $load or $create), you can use it when creating your support object:
```
backend.$bind("tickets").$create({title: "aaa"}).then( function(newTicket) {
  backend.$bind("supports").$create({personInCharge: "notme", ticket: newTicket});
});
```

**Comment by jinyoung** [comment]
I got it.
great abstraction!

Thank you
