### ISSUE TITLE
Please support PATCH method

### ISSUE THREAD

**Issue by jo-narae** [lbovet/hybind#23]
hi. lbovet.
I want PATCH method when request rest service.
Hybind is not currently support PATCH method.
could you support PATCH method?

**Comment by lbovet** [comment]
This is not planned. Mostly because it would require to have a field selection or manage a dirty state which brings a whole lot of complexity.
Or, do you mean something else?

**Comment by jo-narae** [comment]
No, there is no other meaning. Thank you for answer.
