### ISSUE TITLE
How i can load one item

### ISSUE THREAD

**Issue by maksaimer** [lbovet/hybind#5]
Hi,

One question, how i can load one item. I have path for countries:

```
this.api = hybind('/countries');
this.api.$bind(this.path, this.items);
```

How i can load one of countries, for example, with id equals 3 without loading all items from server?

**Comment by lbovet** [comment]
If you want to load your countries one by one and keep them indexed by id, you should do as follows.  Since I have no information about your model, I am assuming that your countries are under /countries/{id} and have a name attribute.

```
countries.$bind('3').$load(function() {
  console.log(countries['3'].name);
});
```

This will load the country id=3 in the countries map and display its name.

You can also of course simply load any resource you know the path to with:

```
hybind('/countries/3').$load().then(function(country) {
 console.log(country.name);
});
```

But this is less hateoas compliant.

**Comment by maksaimer** [comment]
Thank you for good explaining. And last one question.

In out application we have GRUD functions on country (for exemple).

If a want to get list of countries:

```
this.items = [];
this.api.$bind(this.path, this.items);
```

after works with **this.items**

And if i want to edit exists country with id equals 3 (you example):

```
countries.$bind('3').$load(function() {
  var country = countries['3'];
  country.$save().then(function() { /* do some think */ });
});
```

If i want create new item:
`this.items.$create(item)`

What should I do if I want to get equal behavior while creating and updating object? With update I have hybind object which has $save, $create and etc methods, but with create i have simple object `item`

**Comment by lbovet** [comment]
$create returns a promise as well (note I fixed the $load example above, it returns a promise).
If you have the id as attribute of the object:

```
this.items.$create().then(function(item) {  // create the object in the server (POST)
  countries[item.id] = id;  // add it in the countries "cache"
});
```

**Comment by maksaimer** [comment]
I want some like this:

```
var item = this.items.$create();
item.name = 'USA';
item.$save().then(function() {
    /* other logic */
});
```

**Comment by lbovet** [comment]
You can do like this

```
var item = { name: 'USA' };
this.items.$create(item).then(function() {
  /* other logic */
});
```

Or like this

```
this.items.$create().then(function(item) {
  item.name = 'USA';
  return  item.$save();
}).then(function() {
   /* other logic */
});
```

the first one makes only one call to server

**Comment by lbovet** [comment]
Considered answered.
