### ISSUE TITLE
bound array properties are not serialized properly

### ISSUE THREAD

**Issue by nidi3** [lbovet/hybind#9]
```
{
  $bind: ...
  value: 'xxx',
  boundArray: [ 
    {$bind:..., value: 42},
    {$bind:..., value: 666}
  ]
}
```

is serialized into

```
{
  value: "xxx",
  boundArray: [null,null]
}
```

I (and spring data) would expect an empty array or no `boundArray` at all.

**Comment by lbovet** [comment]
If the array has been actually bound (i.e. it has a $bind property itself), it will not appear in the serialized form. Here, we have an array of bound objects, not a bound array of bound objects. Is it done on purpose?
